name: Create Release Assets

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Create the "server.zip" file
      - name: Create "server" zip
        run: |
          mkdir -p release_assets
          zip -r release_assets/server.zip mods/ world/ LICENSE README.md eula.txt server-icon.png server.jar server.properties

      # Create the "world.zip" file without the parent directory
      - name: Create "world" zip
        run: |
          cd world  # Navigate to the 'world' folder
          zip -r ../release_assets/world.zip ./*  # Zip the contents of the 'world' directory without the directory itself

      # Upload the "server" asset (updated to version v2 for Node.js compatibility)
      - name: Upload "server" asset
        uses: actions/upload-release-asset@v2  # Upgraded to v2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release_assets/server.zip
          asset_name: server.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload the "world" asset (updated to version v2 for Node.js compatibility)
      - name: Upload "world" asset
        uses: actions/upload-release-asset@v2  # Upgraded to v2
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: release_assets/world.zip
          asset_name: world.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
